/*
 * slcan_generator.c
 *
 * Generates CAN / CAN FD frames on a fixed period and sends them to
 * the daemon's TX named pipe for one channel, forever until Ctrl+C.
 * Any of ID / data length / data bytes given on the command line
 * stays fixed on every frame; anything left unspecified is
 * re-randomized on every frame (a fresh random ID, or fresh random
 * data, each time).
 *
 * Usage:
 *   slcan_generator.exe [channel] -g <ms> [-f] [-I <id>] [-L <len>] [-D <data>]
 *   slcan_generator.exe -h | --help
 *
 * -g <ms>   Transmission period in milliseconds (default: 200).
 * -f        CAN FD mode. Omit for Classic CAN.
 * -I <id>   CAN ID in hex (e.g. 123 or 1A2B3C4D). 1-7 hex digits is
 *           Standard (11-bit); exactly 8 hex digits is Extended
 *           (29-bit) -- same convention slcan_parse_frame() uses for
 *           candump-style "ID#DATA" text. Omitted: a fresh random
 *           Standard (11-bit) ID every frame.
 * -L <len>  Data length in bytes: 0-8 (Classic) or 0-64 (-f). If -D
 *           is also given they must agree; if -D is given without
 *           -L, the length is taken from -D's byte count. Omitted
 *           (and no -D): a fresh random length every frame.
 * -D <data> Data bytes in hex (e.g. DEADBEEF), even number of hex
 *           digits. Omitted: fresh random data every frame, of
 *           whatever length -L (or the per-frame random length)
 *           resolved to.
 *
 * RTR frames, BRS and ESI are not generated by this tool.
 */

#include <windows.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include "slcan.h"

#define DEFAULT_CHANNEL      "can0"
#define DEFAULT_PERIOD_MS    200
#define PIPE_TX_FORMAT       "\\\\.\\pipe\\serial_tx\\%s"

/* Sleep in short slices rather than one Sleep(ms), so Ctrl+C is
 * noticed within SLEEP_SLICE_MS instead of only at the next period
 * boundary (see console_ctrl_handler()/g_running below). */
#define SLEEP_SLICE_MS       50

static volatile BOOL g_running = TRUE;

static BOOL WINAPI console_ctrl_handler(DWORD ctrl_type)
{
    switch (ctrl_type) {
    case CTRL_C_EVENT:
    case CTRL_BREAK_EVENT:
    case CTRL_CLOSE_EVENT:
        g_running = FALSE;
        return TRUE;
    default:
        return FALSE;
    }
}

/* Sleep for ms milliseconds, but bail out early (before the full
 * duration has elapsed) as soon as g_running is cleared, so a long
 * -g period doesn't delay shutdown after Ctrl+C. */
static void sleep_interruptible(DWORD ms)
{
    while (g_running && ms > 0) {
        DWORD slice = (ms < SLEEP_SLICE_MS) ? ms : SLEEP_SLICE_MS;
        Sleep(slice);
        ms -= slice;
    }
}

static void print_usage(const char *prog)
{
    char pipe_tx_ex[48];
    snprintf(pipe_tx_ex, sizeof(pipe_tx_ex), PIPE_TX_FORMAT, DEFAULT_CHANNEL);

    fprintf(stderr,
        "Usage: %s [channel] [-g <ms>] [-f] [-I <id>] [-L <len>] [-D <data>]\n"
        "       %s -h | --help\n"
        "\n"
        "  channel   CAN channel name, must match the daemon's channel\n"
        "            (letters, digits, '_' or '-' only; default: %s)\n"
        "\n"
        "Options:\n"
        "  -g <ms>   Transmission period in milliseconds (default: %d)\n"
        "  -f        CAN FD mode (default: Classic CAN)\n"
        "  -I <id>   CAN ID in hex, e.g. 123 or 1A2B3C4D.\n"
        "            1-7 hex digits = Standard (11-bit); 8 hex digits =\n"
        "            Extended (29-bit). Omit for a fresh random Standard\n"
        "            ID every frame.\n"
        "  -L <len>  Data length in bytes: 0-8 (Classic) or 0-64 (-f).\n"
        "            Must agree with -D's byte count if both are given.\n"
        "            Omit (with no -D) for a fresh random length every\n"
        "            frame.\n"
        "  -D <data> Data bytes in hex, e.g. DEADBEEF (even number of hex\n"
        "            digits). If -L is omitted, the length is taken from\n"
        "            -D. Omit for fresh random data every frame.\n"
        "\n"
        "Any of -I/-L/-D you provide stays fixed on every frame; anything\n"
        "you omit is re-randomized on every frame. Sends one frame every\n"
        "<ms> milliseconds to the daemon's TX named pipe for channel\n"
        "(e.g. %s) until Ctrl+C. RTR frames, BRS and ESI are not\n"
        "generated by this tool.\n"
        "\n"
        "serial_daemon.exe must already be running for that channel\n"
        "(physical or --vcan).\n"
        "\n"
        "Options:\n"
        "  -h, --help   Show this help message and exit\n",
        prog, prog, DEFAULT_CHANNEL, DEFAULT_PERIOD_MS, pipe_tx_ex);
}

/* Decode one ASCII hex byte "XX" at p[0..1]. Caller must already have
 * validated both chars are hex digits (see parse_hex_data below). */
static uint8_t hex2byte(const char *p)
{
    char hex[3] = { p[0], p[1], '\0' };
    return (uint8_t)strtoul(hex, NULL, 16);
}

/* Parse an -I argument: a hex CAN ID string. Sets *id and *ext per
 * the digit-count convention used elsewhere in this project (exactly
 * 8 hex digits = Extended, otherwise Standard -- see
 * slcan_parse_frame() in slcan.c), and range-checks the result
 * against CAN_SFF_ID_MAX/CAN_EFF_ID_MAX. Returns 0 on success, -1 on
 * any parse/range error. */
static int parse_hex_id(const char *s, uint32_t *id, uint8_t *ext)
{
    size_t len = strlen(s);
    if (len == 0 || len > 8) return -1;
    for (size_t i = 0; i < len; i++) {
        if (!isxdigit((unsigned char)s[i])) return -1;
    }

    unsigned long v = strtoul(s, NULL, 16);
    *ext = (len == 8) ? 1 : 0;
    uint32_t max_id = *ext ? CAN_EFF_ID_MAX : CAN_SFF_ID_MAX;
    if (v > max_id) return -1;

    *id = (uint32_t)v;
    return 0;
}

/* Parse an -L argument: a decimal byte count, range-checked against
 * maxlen (8 for Classic, SLCAN_FD_MAX_DLEN for -f). Returns 0 on
 * success, -1 on any parse/range error. */
static int parse_len(const char *s, uint8_t maxlen, uint8_t *out)
{
    if (!s || *s == '\0') return -1;
    char *end = NULL;
    long v = strtol(s, &end, 10);
    if (end == s || *end != '\0') return -1;
    if (v < 0 || v > (long)maxlen) return -1;
    *out = (uint8_t)v;
    return 0;
}

/* Parse a -D argument: a hex data string (even number of hex digits,
 * at most SLCAN_FD_MAX_DLEN bytes). Fills data[0..len-1] and sets
 * *len. Returns 0 on success, -1 on any parse/range error. */
static int parse_hex_data(const char *s, uint8_t *data, uint8_t *len)
{
    size_t slen = strlen(s);
    if (slen == 0 || (slen % 2) != 0) return -1;
    size_t nbytes = slen / 2;
    if (nbytes > SLCAN_FD_MAX_DLEN) return -1;

    for (size_t i = 0; i < slen; i++) {
        if (!isxdigit((unsigned char)s[i])) return -1;
    }
    for (size_t i = 0; i < nbytes; i++)
        data[i] = hex2byte(s + i * 2);

    *len = (uint8_t)nbytes;
    return 0;
}

int main(int argc, char *argv[])
{
    const char *prog = (argc > 0 && argv[0][0] != '\0') ? argv[0]
                                                          : "slcgen.exe";

    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0 ||
            strcmp(argv[i], "/?") == 0) {
            print_usage(prog);
            return 0;
        }
    }

    const char *ch          = DEFAULT_CHANNEL;
    BOOL        ch_set       = FALSE;
    BOOL        fd_mode      = FALSE;
    DWORD       period_ms    = DEFAULT_PERIOD_MS;

    BOOL        have_id      = FALSE;
    uint32_t    fixed_id     = 0;
    uint8_t     fixed_ext    = 0;

    BOOL        have_len     = FALSE;
    uint8_t     fixed_len    = 0;

    BOOL        have_data    = FALSE;
    uint8_t     fixed_data[SLCAN_FD_MAX_DLEN];
    uint8_t     data_len_from_d = 0;

    for (int i = 1; i < argc; i++) {
        const char *arg = argv[i];

        if (strcmp(arg, "-g") == 0) {
            if (++i >= argc) {
                fprintf(stderr, "[generator] Error: -g requires a value\n\n");
                print_usage(prog);
                return 1;
            }
            char *end = NULL;
            long  v   = strtol(argv[i], &end, 10);
            if (end == argv[i] || *end != '\0' || v <= 0) {
                fprintf(stderr,
                        "[generator] Error: invalid -g value '%s' "
                        "(must be a positive integer)\n\n", argv[i]);
                print_usage(prog);
                return 1;
            }
            period_ms = (DWORD)v;

        } else if (strcmp(arg, "-f") == 0) {
            fd_mode = TRUE;

        } else if (strcmp(arg, "-I") == 0) {
            if (++i >= argc) {
                fprintf(stderr, "[generator] Error: -I requires a value\n\n");
                print_usage(prog);
                return 1;
            }
            if (parse_hex_id(argv[i], &fixed_id, &fixed_ext) != 0) {
                fprintf(stderr,
                        "[generator] Error: invalid -I value '%s' "
                        "(1-8 hex digits, in range)\n\n", argv[i]);
                print_usage(prog);
                return 1;
            }
            have_id = TRUE;

        } else if (strcmp(arg, "-L") == 0) {
            if (++i >= argc) {
                fprintf(stderr, "[generator] Error: -L requires a value\n\n");
                print_usage(prog);
                return 1;
            }
            /* fd_mode may not be parsed yet if -f comes later on the
             * command line; re-validated against the final fd_mode
             * right after the parse loop below. */
            if (parse_len(argv[i], SLCAN_FD_MAX_DLEN, &fixed_len) != 0) {
                fprintf(stderr,
                        "[generator] Error: invalid -L value '%s'\n\n",
                        argv[i]);
                print_usage(prog);
                return 1;
            }
            have_len = TRUE;

        } else if (strcmp(arg, "-D") == 0) {
            if (++i >= argc) {
                fprintf(stderr, "[generator] Error: -D requires a value\n\n");
                print_usage(prog);
                return 1;
            }
            if (parse_hex_data(argv[i], fixed_data, &data_len_from_d) != 0) {
                fprintf(stderr,
                        "[generator] Error: invalid -D value '%s' "
                        "(even number of hex digits, max %d bytes)\n\n",
                        argv[i], SLCAN_FD_MAX_DLEN);
                print_usage(prog);
                return 1;
            }
            have_data = TRUE;

        } else if (arg[0] != '-' && !ch_set) {
            if (!slcan_valid_channel(arg)) {
                fprintf(stderr,
                        "[generator] Error: invalid channel name '%s' "
                        "(use letters, digits, '_' or '-', non-empty)\n\n",
                        arg);
                print_usage(prog);
                return 1;
            }
            ch     = arg;
            ch_set = TRUE;

        } else {
            fprintf(stderr, "[generator] Error: unrecognized argument '%s'\n\n",
                    arg);
            print_usage(prog);
            return 1;
        }
    }

    uint8_t maxlen = fd_mode ? SLCAN_FD_MAX_DLEN : SLCAN_MAX_DLEN;

    if (have_len && fixed_len > maxlen) {
        fprintf(stderr,
                "[generator] Error: -L %d exceeds the %d-byte limit for %s\n\n",
                fixed_len, maxlen, fd_mode ? "CAN FD" : "Classic CAN");
        print_usage(prog);
        return 1;
    }
    if (have_data && data_len_from_d > maxlen) {
        fprintf(stderr,
                "[generator] Error: -D is %d bytes, exceeds the %d-byte "
                "limit for %s\n\n",
                data_len_from_d, maxlen, fd_mode ? "CAN FD" : "Classic CAN");
        print_usage(prog);
        return 1;
    }
    if (have_len && have_data && fixed_len != data_len_from_d) {
        fprintf(stderr,
                "[generator] Error: -L %d does not match -D's byte count (%d)\n\n",
                fixed_len, data_len_from_d);
        print_usage(prog);
        return 1;
    }
    if (have_data && !have_len) {
        fixed_len = data_len_from_d;
        have_len  = TRUE;   /* -D without -L fixes the length too */
    }

    char pipebuf[32];
    int  need = snprintf(pipebuf, sizeof(pipebuf), PIPE_TX_FORMAT, ch);
    if (need < 0 || need >= (int)sizeof(pipebuf)) {
        fprintf(stderr, "[generator] Error: channel name too long: %s\n", ch);
        return 1;
    }

    if (!WaitNamedPipeA(pipebuf, 5000)) {
        fprintf(stderr, "[generator] daemon not running for channel '%s'\n", ch);
        return 1;
    }
    HANDLE hPipe = CreateFileA(pipebuf, GENERIC_WRITE, 0, NULL,
                               OPEN_EXISTING, 0, NULL);
    if (hPipe == INVALID_HANDLE_VALUE) {
        fprintf(stderr, "[generator] Cannot open pipe: %lu\n", GetLastError());
        return 1;
    }

    if (!SetConsoleCtrlHandler(console_ctrl_handler, TRUE))
        fprintf(stderr,
                "[generator] WARNING: could not install Ctrl+C handler (%lu); "
                "Ctrl+C will terminate without cleanup\n", GetLastError());

    srand(GetTickCount() ^ GetCurrentProcessId());

    fprintf(stderr,
            "[generator] Sending to channel '%s' every %lu ms (%s). "
            "Press Ctrl+C to stop.\n",
            ch, (unsigned long)period_ms, fd_mode ? "CAN FD" : "Classic CAN");

    DWORD    written;
    CanFrame frame;

    while (g_running) {
        memset(&frame, 0, sizeof(frame));
        frame.fd  = fd_mode ? 1 : 0;
        frame.rtr = 0;
        frame.brs = 0;
        frame.esi = 0;

        if (have_id) {
            frame.id  = fixed_id;
            frame.ext = fixed_ext;
        } else {
            frame.id  = (uint32_t)(rand() % (CAN_SFF_ID_MAX + 1));
            frame.ext = 0;
        }

        uint8_t len;
        if (have_len) {
            len = fixed_len;
        } else if (fd_mode) {
            /* pick a random CAN FD DLC code, then its data length,
             * so the length always lands on one of the FD-valid
             * byte counts (0,1..8,12,16,20,24,32,48,64) instead of
             * an arbitrary 0-64 integer */
            len = canfd_dlc2len((uint8_t)(rand() % (CANFD_MAX_DLC + 1)));
        } else {
            len = (uint8_t)(rand() % (SLCAN_MAX_DLEN + 1));
        }
        frame.len = len;

        if (have_data) {
            memcpy(frame.data, fixed_data, len);
        } else {
            for (int i = 0; i < len; i++)
                frame.data[i] = (uint8_t)(rand() % 256);
        }

        if (!WriteFile(hPipe, &frame, sizeof(frame), &written, NULL)
            || written != sizeof(frame)) {
            fprintf(stderr, "[generator] pipe write error: %lu\n",
                    GetLastError());
            break;
        }

        sleep_interruptible(period_ms);
    }

    fprintf(stderr, "[generator] Stopped.\n");
    CloseHandle(hPipe);
    return 0;
}
